### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by dili021** [dili021/rails-capstone#2]
Feel free to leave some comments

**Comment by patriciachrysy** [comment]
Good job partner, your validators in the user class are impressive!!! Also like Tailwind, seem to have more features that bootstrap, I'll try it only portfolio. Maybe you should also think about adding some validators to Following model too, in order to avoid auto-following and double following.

**Comment by rammazzoti2000** [comment]
Hey Stefan I only managed to review the models and obviously with limitations based on my knowledge I have the following suggestions:

- In the user model you can add the includes eager loader to avoid n+1 queries
```
def my_timeline
    followed_user_ids = []
    followed_users.each { |user| followed_user_ids << user.id }
    Recipe.where(author: followed_user_ids + [id]).includes(:author)
  end
```
- In the following model you can combine the validations in a single line 
```
validates :follower_id, :followed_id, presence: true
```
Otherwise the project is quite solid, and the style you were able to generate with only tailwind is impressive, good job.

**Comment by nyatindopatrick** [comment]
Alex just pointed out what I noticed as well. Nice work.

**Comment by dili021** [comment]
Thanks for the comments everyone!
@patriciachrysy I dealt with the following issue by not rendering the follow button on own page, and by switching between follow/unfollow on other user's pages.
@rammazzoti2000 the includes for that case are in the controller that renders `my_timeline`. It is better to have as little code in the controllers as possible so I'll move it, thanks for the tip.
Ditto for the validations.

**Comment by patriciachrysy** [comment]
@dili021  i did it too, but you still have t put it in model because someone can access the controller using the browser address bar or any API access. The security has to be on all levels.

**Comment by rammazzoti2000** [comment]
@dili021 Sorry haven't seen that :+1:

**Comment by dili021** [comment]
@rammazzoti2000 also, I just remembered belongs_to is an implicit validator of presence: true, so it can actually be removed entirely.
